# Generated by Django 5.1.7 on 2025-05-28 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
