# Generated by Django 5.1.7 on 2025-08-01 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
